language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
install:
    - pip install . -UI
    - pip install -r requirements.txt -UI
    - pip install pytest
    - pip install pytest-pep8
script: 
    - py.test --pep8 .
    - ./define/define.py test

