language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
sudo: required
before_install:
    - sudo apt-get install -qq python-requests
install:
    - pip install -r requirements.txt
    - pip install pytest
    - pip install pytest-pep8
script: 
    - py.test --pep8 .
    - ./define/define.py -k test

